---
- name: "Update Ubuntu packages"
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: "Installing bind"
  apt:
    name: ["{{ bind_name }}"]
    state: latest

- name: "Checking if bind is installed"
  apt:
    name: ["{{ bind_name }}"]
    state: present
  notify:
    - enable_named
    - start_named

- name: "Copying forward.{{ domain_sufix }}"
  copy:
    src: "files/forward.{{ domain_sufix }}"
    dest: "{{ bind_dir }}/forward.{{ domain_sufix }}"

- name: "Copying reverse.{{ domain_sufix }}"
  copy:
    src: "files/reverse.{{ domain_sufix }}"
    dest: "{{ bind_dir }}/reverse.{{ domain_sufix }}"

- name: "Copying named.conf.local"
  copy:
    src: "files/named.conf.local"
    dest: "{{ bind_dir }}/named.conf.local"

- name: "Copying named.conf.options"
  copy:
    src: "files/named.conf.options"
    dest: "{{ bind_dir }}/named.conf.options"
  notify:
    - restart_named
