---

# - name: "Set up the repository"
#   shell: apt-get update -y

- name: "Set up the repository"
  apt:
    name:
      - "{{ ca_certificates_package }}"
      - "{{ curl_package }}"
      - "{{ gnupg_package }}"
      - "{{ lsb_release_package }}"
    state: latest
    update_cache: yes

- name: "Confirms Set up the repository"
  apt:
    name:
      - "{{ ca_certificates_package }}"
      - "{{ curl_package }}"
      - "{{ gnupg_package }}"
      - "{{ lsb_release_package }}"
    state: present

- name: "Add Docker’s official GPG key:"
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: "Use the following command to set up the stable repository"
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null


- name: "Set up the repository"
  apt:
    name:
      - "{{ docker_ce_package }}"
      - "{{ docker_ce_cli_package }}"
      - "{{ containerd_io_package }}"
    state: latest
    update_cache: yes

- name: "Set up the repository"
  apt:
    name:
      - "{{ docker_ce_package }}"
      - "{{ docker_ce_cli_package }}"
      - "{{ containerd_io_package }}"
    state: present

- name: "Reinicio do serviço Docker"
  systemd:
    name: "{{ docker_service }}"
    enabled: yes

- name: "Reinicio do serviço containerd"
  systemd:
    name: "{{ containerd_service }}"
    enabled: yes

- name: "Cria o caminho para o serviço systemD"
  shell: mkdir -p "{{ docker_service_path }}"

- name: "Cópia de configuração de escutar na porta 0.0.0.0"
  copy:
    src: files/override.conf
    dest: "{{ docker_service_path }}/override.conf"
    owner: "{{ sudo_user }}"
    group: "{{ sudo_user }}"
    mode: "0755"

- name: "Reincio do daemon para aplicar efeitos"
  shell: systemctl daemon-reload

- name: "Reinicio do serviço Docker"
  service:
    name: "{{ docker_service }}"
    state: restarted

# - name: "Reinicio do serviço Containerd"
#   service:
#     name: "{{ containerd.service }}"
#     state: restarted

- name: "Concede permissão {{ docker_group }} ao usuário {{ my_user}}"
  shell: usermod -aG "{{ docker_group }}" "{{ my_user}}"

- name: "Baixa docker-compose 1.29.2"
  shell: curl -L "{{ docker_compose_url }}" -o "{{ docker_compose_path }}"

- name: "Concede permissão de execução ao Compose"
  shell: chmod +x "{{ docker_compose_path }}"

- name: "Criar link para execução do Compose"
  shell: ln -s "{{ docker_compose_path }}" /usr/bin/docker-compose
