---
- name: "Instalando o NGINX"
  yum:
    name: nginx
    state: latest

- name: "Confirmando a instalação do NGINX"
  yum:
    name: nginx
    state: present

- name: "[NGINX] Start's nginx service"
  become: yes
  service:
    name: nginx
    state: started

- name: "[NGINX] Enables nginx service"
  become: yes
  systemd:
    name: nginx
    enabled: yes
