---
- name: "[NGINX] UPDATE CENTOS 8"
  become: yes
  shell: yum update -y

- name:  "[NGINX] Instala o nginx"
  become: yes
  yum:
    name: nginx
    state: latest

- name: "[NGINX] HTTP SERVICE FIREWALL"
  become: yes
  shell: firewall-cmd --add-service=http --permanent

- name: "[NGINX] RELOAD FIREWALL"
  become: yes
  shell: firewall-cmd --reload


