---
- name: "Installing NGINX"
  apt:
    name: "{{ nginx_name }}"
    state: latest

- name: "Checking if NGINX is installed"
  apt:
    name: "{{ nginx_name }}"
    state: present
  notify:
    - enable_nginx
    # - start_nginx

- name: "Copying locations.conf to {{ nginx_dir }}/locations.conf"
  copy:
    src: "files/locations.conf"
    dest: "{{ nginx_dir }}/locations.conf"
  # notify: restart_nginx
