---
- name: Atualizando o repositório do CentOs.
  shell: dnf -y update

- name: Instalando pacotes básicos para o servidor.
  yum:
    state: latest
    name: [ {{ pacotes_basico_de_instalacao }}]

- name: Verificando a instalação dos pacotes básicos para o servidor.
  yum:
    state: present
    name: [ {{ pacotes_basico_de_instalacao }}]

- name: Copiando o repositório de instalação do VirtualBox.
  copy:
    src: files/VirtalBox.repo
    dest: {{dir_repositorio}}/VirtualBox.repo  

- name: Copiando o repositório de instalação do Hashicorp.
  copy:
    src: files/Hashicorp.repo
    dest: {{dir_repositorio}}/Hashicorp.repo

- name: Instalando {{ virtualbox }}
  yum:
    name: [{{ virtualbox }}]
    state: latest

- name: Confirmando a instalação {{ virtualbox }}
  yum:
    name: [{{ virtualbox }}]
    state: present